name: FOSSA License Scan

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run FOSSA Scan
        uses: fossas/fossa-action@v1
        with:
          # Passa a chave da API do FOSSA que configuramos como um secret
          api-key: ${{ secrets.FOSSA_API_KEY }}
