name: SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # O Sonar precisa do histórico completo para analisar novos códigos
          fetch-depth: 0

      - name: SonarCloud Scan
        # ALTERAÇÃO PRINCIPAL: Trocamos @master pela versão estável @v2
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          # Passa o token do GitHub para a action (necessário para PRs)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Passa o token do Sonar que configuramos
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}